#
# Copyright 2017 The Jaeger Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

apiVersion: v1
kind: Template
metadata:
  name: jaeger-agent-template
  annotations:
    description: Jaeger Agent
    iconClass: icon-go-gopher
    openshift.io/display-name: Jaeger-Agent
    tags: instant-app,tracing,opentracing,jaeger,agent
parameters:
- description: The name of the Jaeger Service.
  displayName: Jaeger Service Name
  name: JAEGER_SERVICE_NAME
  required: true
  value: jaeger
- description: The Jaeger image version to use
  displayName: Image version
  name: IMAGE_VERSION
  required: false
  value: "0.5"

labels:
  template: jaeger-agent

objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${JAEGER_SERVICE_NAME}-agent
    labels:
      app: jaeger
      jaeger-infra: agent-service
  spec:
    ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    selector:
      jaeger-infra: ${JAEGER_SERVICE_NAME}-agent
    clusterIP: None

- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: ${JAEGER_SERVICE_NAME}-agent
    labels:
      app: jaeger
      jaeger-infra: ${JAEGER_SERVICE_NAME}-agent-deployment
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: jaeger
          jaeger-infra: ${JAEGER_SERVICE_NAME}-agent
      spec:
        containers:
        - name: agent-instance
          image: jaegertracing/jaeger-agent:${IMAGE_VERSION}
          imagePullPolicy: Always
          command:
          - "/go/bin/agent-linux"
          - "--collector.host-port=jaeger-collector:14267"
          ports:
          - containerPort: 5775
            protocol: UDP
          - containerPort: 6831
            protocol: UDP
          - containerPort: 6832
            protocol: UDP
